# Generated by Django 5.2.12 on 2026-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme', models.CharField(max_length=155)),
                ('color', models.CharField(max_length=155)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
