# Generated by Django 5.2.12 on 2026-04-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='neme',
            new_name='name',
        ),
    ]
