# Generated by Django 5.2.12 on 2026-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_neme_car_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=155)),
                ('price', models.CharField(max_length=155)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
